fix use of deprecated include: boost/exception.hpp
make process said:

/usr/include/boost/exception.hpp:9:2: error: #error The header
<boost/exception.hpp> has been deprecated. Please #include
<boost/exception/all.hpp> instead.